name: Build PBR

on:
  schedule:
    - cron: "2 15 */1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: download cidr
      run: |
        curl -sLo ali.rsc https://ali-us-ip.v2r4frank.workers.dev/as45102
        chmod +x ros-dpbr.sh
        ./ros-dpbr.sh
        
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
